name: spatially
version: 0.0.1
author: Thomas Stephenson
description: A sample web application
homepage: www.github.com/dart-spatially
dependencies:
  longdouble: any
  quiver: any
  unittest: '>=0.9.0'
