name: spatially
author: Thomas Stephenson
version: 0.1.1
homepage: www.github.com/dart-spatially
description: A sample web application
dependencies:
  collection: '^1.14.0'
  longdouble: any
  quiver: any
dev_dependencies:
  test: '^0.12.0'
  benchmark_harness: any
