name: spatially
author: Thomas Stephenson
version: 0.1.0
homepage: www.github.com/dart-spatially
description: A sample web application
dependencies:
  collection: any
  longdouble: any
  quiver: any
  unittest: '>=0.9.0'
dev_dependencies:
  benchmark_harness: any
